
let colorByLabel = {
    'blue-ish': [],
    'green-ish': [],
    'pink-ish': [],
    'grey-ish': [],
    'red-ish': [],
    'purple-ish': [],
    'brown-ish': [],
    'orange-ish': [],
    'yellow-ish': [],
  }
  
  //definition for type to display in visualising by color function
  let label = 'blue-ish';
  
  
  function setup() {
    noCanvas();
  
  
    // Initialize Firebase

    //this one is mine, but it's generated by one user so i'm gonna use conding train fireabase
    var config = {
        apiKey: "AIzaSyDPekCKX4ee6h9NVR2lEITGAM0XIHn-c7c",
        authDomain: "color-classification.firebaseapp.com",
        databaseURL: "https://color-classification.firebaseio.com",
        projectId: "color-classification",
        storageBucket: "",
        messagingSenderId: "590040209608"
      };
    firebase.initializeApp(config);
    database = firebase.database();
    let ref = database.ref('colors');
    ref.once('value', gotData);

  }
  
  function gotData(results) {
    let data = results.val();

    let allData = {
      entries: []
    };

    // Processing data
    let keys = Object.keys(data);

    for (let key of keys) {
      let record = data[key];

      let id = record.uid;
      if (!filter[id]) {
        allData.entries.push(record);
      }
    }
  
    saveJSON(allData,'colorData.json');

    //possible noisy users
    //BeriXSWj1LbzWMOoHYbYgfw4SGA3
    //YGdqOTDDmrbGm80gM5UHicxMBgS2
    //HUXmyv1dSSUnIvYk976MPWUSaTG2

  
}